vich_uploader:
    db_driver: orm
    mappings:
        uploads_file:
            uri_prefix:         '/uploads/documents'
            upload_destination: '%kernel.project_dir%/public/uploads/documents'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            namer: vich_uploader.namer_origname
